---
title: "Project proposal 2"
author: "Michael"
date: 2019-01-21
output: 
  github_document:
    toc: true
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview:

#### Summary

This project draws a relationship between where children grow up and whether or
not they "prosper" as adults.  Specifically, this project develops an
interactive map which includes every census tract in the United States as well
as the expected adult household earnings for a child who grew up in a given
tract.  The project is currently being used to make judgements about the factors
that influence such a finding, and further, how policy can be used to place
children in better neighborhood, something which I am curious to learn more
about.

#### Data Description

The data utilizes information from a vast array of sources and includes factors
such as: household incomes and incarceration rates; race, gender, and parental
income; as well as neighborhood characteristics, each at the census tract, 
county, and commuting zone level.

#### Goals

My personal goals for this project are to recreate the interactive map, 
including the income predictions, and gain a better understanding of the
factors that went into making such a prediction.  It would also be interesting 
to explore relationships between the various predictive factors and the
outcomes, as well as map any findings onto the map I create.  Additional
goals may arise as I explore the data and gain a better understanding of the
author's methodology.


## Links:

#### Data Source(s)

* Excel csv files: https://opportunityinsights.org/data/?geographic_level=0&topic=0&paper_id=1652#resource-listing

#### Original Work

* Original Paper: https://opportunityinsights.org/wp-content/uploads/2018/10/atlas_paper.pdf

* Opportunity Insights Webpage: https://opportunityinsights.org/paper/the-opportunity-atlas/

* Opportunity Atlas (Map): https://www.opportunityatlas.org/

* NYT Article: https://www.nytimes.com/2018/10/01/upshot/maps-neighborhoods-shape-child-poverty.html


## Potential Challenge:

A potential challenge stemming from this data could have the team attempt to
understand the relationship between household tracts and future household 
incomes.  Once they understand the effects that various tracts have on income
and opportunity, they can explore a few of the characteristics of the tracts and
their relationship with upward mobility.  For instance, they could explore the
relationship between housing costs and mobility opportunities.  They could then
further explore variations in these relationships across demographic factors
such as race and parental income.

---
## Project Timeline:
  
#### Progress Report 1 (week 4)

For this report, I plan to analyze and explore very general nationwide trends in
the data.  The goal of this report is to begin familiarizing myself with these
larger trends and gain insights into variations in the data across various
demographic factors such as race, and income.  Example trends include
household incomes for children who grew up in certain tracts, as well as the
incarceration rates for those tracts.

**Deliverables** in this report include static maps of the nation as a whole,
various cities/counties of interest, and plots showing the basic relationships
between the variables I have explored.

#### Progress Report 2 (week 6)

For this progress report, I will analyze deeper trends in the data stemming from
factors such as poverty rates, housing costs, and economic growth indicators
within each tract.  Where it makes sense, I will explore relationships between
these factors and attempt to understand how they jointy affect key opportunity
measures such as the future household incomes and employment rates of children
growing up in these tracts.  By this point, I would like to explore and recreate
several of the most interesting findings of the report, which highlight
relationships between key factors such as those described above.

**Deliverables** in this reprort include several different plots analyzing the
relationship between the factors mentioned above, as well as descriptions and
hypothesis as to what effect those relationships may have.  Some plots in this
report will also compare said relationships across cities, regions, or race to
get a sense for the variability in the data.

#### Challenge for Rest of Team (week 7)

The goal of this challenge will not be to present the team with an impossible
task, but rather to guide them through exploring some very interesting data and
help them to draw interesting conclusions about its potential implications.

#### Final Report (week 9)

The goal of my final report will be to replicate several of the results that the
original work did, as well as, further explore the aspects of the data related
to education.  The final report will build off of my previous reports by adding
my own analysis of educational factors such as high school graduation rates,
college education rates, and hopefully, exploring the feasibility of moving
families to better neighborhoods for the sake of better educational
opportunities.


